### ISSUE TITLE
Semantic Link - Auth Issue?

### ISSUE THREAD

**Issue by mtworth** [microsoft/semantic-link-functions#16]
I have been running a notebook weekly that pulls data from a semantic model into a pandas dataframe using semantic-link. 

When I ran the code snippet below, I received an error for the first time: 
 

`import sempy.fabric as fabric df_datasets = fabric.list_datasets(workspace="Analytics Workbench")
` 

`ModuleNotFoundError: No module named 'notebookutils.credentials'
` 
This happens in 0.7.3, not 0.7.2.

**Comment by eisber** [comment]
fixed w/ 0.7.4
